# Generated by Django 3.2.14 on 2022-07-10 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220708_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_num',
            field=models.PositiveIntegerField(blank=True, default=0, unique=True, verbose_name='account num'),
        ),
    ]
